name: glados-checkin

on:
  workflow_dispatch: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Checkin
      run: |
        python3 checkin.py 
