name: glados-checkin

on:
  schedule:
    - cron:  '0 6,12,20 * * *'
    
jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Checkin
      run: |
        python3 check_in.py 
