name: glados-checkin

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '10/5 * * * *'
    
jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Checkin
      run: |
        python3 check_in.py 
